import standard from '@features/resume/templates/standard';
import standard2 from '@features/resume/templates/standard2';
import template7 from '@features/resume/templates/template-7';
import template1 from '@features/resume/templates/template1';
import template10 from '@features/resume/templates/template10';
import template11 from '@features/resume/templates/template11';
import template12 from '@features/resume/templates/template12';
import template13 from '@features/resume/templates/template13';
import template2 from '@features/resume/templates/template2';
import template3 from '@features/resume/templates/template3';
import template4 from '@features/resume/templates/template4';
import template5 from '@features/resume/templates/template5';
import template6 from '@features/resume/templates/template6';
import template8 from '@features/resume/templates/template8';
import template9 from '@features/resume/templates/template9';

export const mockTemplates = [
  {
    id: '1',
    slug: 'classic-red',
    name: 'Classic Red',
    style: 'Traditional',
    layout: 'Single',
    profession: ['Backend', 'Frontend'],
    color: '#C5244E',
    thumbnail_url: 'https://picsum.photos/seed/template-1/300/400',
    json: template1,
    publicImageUrl: 'https://picsum.photos/seed/template-1/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'creative-sidebar',
    name: 'Creative Sidebar',
    style: 'Creative',
    layout: 'Double',
    profession: ['Designer'],
    color: '#3DB482',
    thumbnail_url: 'https://picsum.photos/seed/template-2/300/400',
    json: template2,
    publicImageUrl: 'https://picsum.photos/seed/template-2/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'modern-blue',
    name: 'Modern Blue',
    style: 'Modern',
    layout: 'Single',
    profession: ['Backend', 'Designer'],
    color: '#005FF2',
    thumbnail_url: 'https://picsum.photos/seed/template-3/300/400',
    json: template3,
    publicImageUrl: 'https://picsum.photos/seed/template-3/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'with-photo-purple',
    name: 'Purple Portrait',
    style: 'With photo',
    layout: 'Double',
    profession: ['Designer', 'Frontend'],
    color: '#6927B3',
    thumbnail_url: 'https://picsum.photos/seed/template-4/300/400',
    json: template4,
    publicImageUrl: 'https://picsum.photos/seed/template-4/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'without-photo-minimal',
    name: 'Clean Minimal',
    style: 'Without photo',
    layout: 'Single',
    profession: ['Backend', 'Frontend'],
    color: '#16C5F5',
    thumbnail_url: 'https://picsum.photos/seed/template-5/300/400',
    json: template5,
    publicImageUrl: 'https://picsum.photos/seed/template-5/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'traditional-double',
    name: 'Executive Double',
    style: 'Traditional',
    layout: 'Double',
    profession: ['Backend'],
    color: '#F03126',
    thumbnail_url: 'https://picsum.photos/seed/template-6/300/400',
    json: template6,
    publicImageUrl: 'https://picsum.photos/seed/template-6/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'creative-yellow',
    name: 'Bold Yellow',
    style: 'Creative',
    layout: 'Single',
    profession: ['Designer', 'Frontend'],
    color: '#FFBE1B',
    thumbnail_url: 'https://picsum.photos/seed/template-7/300/400',
    json: template7,
    publicImageUrl: 'https://picsum.photos/seed/template-7/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    slug: 'modern-pink',
    name: 'Modern Pink',
    style: 'Modern',
    layout: 'Double',
    profession: ['Designer'],
    color: '#D52078',
    thumbnail_url: 'https://picsum.photos/seed/template-8/300/400',
    json: template8,
    publicImageUrl: 'https://picsum.photos/seed/template-8/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    slug: 'with-photo-red',
    name: 'Portrait Red',
    style: 'With photo',
    layout: 'Single',
    profession: ['Frontend', 'Designer'],
    color: '#C5244E',
    thumbnail_url: 'https://picsum.photos/seed/template-9/300/400',
    json: template9,
    publicImageUrl: 'https://picsum.photos/seed/template-9/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    slug: 'without-photo-dark',
    name: 'Dark Minimal',
    style: 'Without photo',
    layout: 'Double',
    profession: ['Backend', 'Frontend'],
    color: '#005FF2',
    thumbnail_url: 'https://picsum.photos/seed/template-10/300/400',
    json: template10,
    publicImageUrl: 'https://picsum.photos/seed/template-10/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    slug: 'traditional-green',
    name: 'Traditional Green',
    style: 'Traditional',
    layout: 'Single',
    profession: ['Backend', 'Designer'],
    color: '#3DB482',
    thumbnail_url: 'https://picsum.photos/seed/template-11/300/400',
    json: template11,
    publicImageUrl: 'https://picsum.photos/seed/template-11/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    slug: 'creative-cyan',
    name: 'Creative Cyan',
    style: 'Creative',
    layout: 'Single',
    profession: ['Frontend', 'Designer'],
    color: '#16C5F5',
    thumbnail_url: 'https://picsum.photos/seed/template-12/300/400',
    json: template12,
    publicImageUrl: 'https://picsum.photos/seed/template-12/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '13',
    slug: 'modern-yellow',
    name: 'Modern Yellow',
    style: 'Modern',
    layout: 'Double',
    profession: ['Backend', 'Frontend'],
    color: '#FFBE1B',
    thumbnail_url: 'https://picsum.photos/seed/template-13/300/400',
    json: template13,
    publicImageUrl: 'https://picsum.photos/seed/template-13/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    slug: 'with-photo-green',
    name: 'Portrait Green',
    style: 'With photo',
    layout: 'Single',
    profession: ['Designer'],
    color: '#3DB482',
    thumbnail_url: 'https://picsum.photos/seed/template-14/300/400',
    json: standard,
    publicImageUrl: 'https://picsum.photos/seed/template-14/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    slug: 'without-photo-purple',
    name: 'Clean Purple',
    style: 'Without photo',
    layout: 'Double',
    profession: ['Backend', 'Designer'],
    color: '#6927B3',
    thumbnail_url: 'https://picsum.photos/seed/template-15/300/400',
    json: standard2,
    publicImageUrl: 'https://picsum.photos/seed/template-15/600/800',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
